### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by defypp** [andyzeng/visual-pushing-grasping#1]
while running main.py, after some training steps, I got the ｅｒｒｏｒ described in title. IndexError: list index out of range. I want to know the error caused by env or code?
My enviroment: ubuntu16.04 with Intel® Xeon(R) CPU E5-1620 v3 @ 3.50GHz × 8 , cuda8.0 installed(no cudnn) with NVIDIA GTX 1080TI.

**Comment by defypp** [comment]
![vpg](https://user-images.githubusercontent.com/13146502/40409180-99162690-5e9c-11e8-8ce8-7e87f6471990.png)

**Comment by andyzeng** [comment]
This error most likely comes from the env in V-REP. The python function `add_objects()` in robot.py calls a lua script in V-REP (called `importShape()` in the scene object `remoteApiCommandServer`) to add objects to the simulation. Something might've interrupted that script. Does the console log on the bottom of the V-REP window show any errors?

I did a fresh install on another Ubuntu 16.04 machine with CUDA 8.0 but was unfortunately unable to reproduce your error.

**Comment by defypp** [comment]
V-rep operation about "Dynamics content " causes the index error in my env, I test the following situation. Open v-rep and main.py, then "Dynamics content " dialog window pop out, if I hesitate to click the window  more than maybe 5 secs, The index error  comes in terminal, as I have to response to the window three times,  accidental I got that Index error. Now, it works fine to me.

**Comment by TONG369** [comment]
Hello,
 Recently I am also using this code to do robot pushing and grasping, is it convenient to leave a contact? Let us communicate and learn together. Thank you, are you Chinese? I am, my mailbox is 1563845456@qq.com, I am looking forward to your reply.
 Thanks,
