### ISSUE TITLE
support-pytorch-v0.4 branch: CUDA out of memory with 1080Ti 11GB memory

### ISSUE THREAD

**Issue by Kelvinson** [andyzeng/visual-pushing-grasping#12]
Hi, thanks for your great work,  I want to run the code and use the following setup:
branch: support-pytorch-v0.4 branch 
Python: Anaconda Python 3.6.5
Pytorch: 1.0.0 
V-REP: v3.6
GPU: 1080Ti 11GB Memory
OS: Ubuntu 16.04 

I have 11GB memory but still come across the GPU memory problem.

![run_out_of_memory](https://user-images.githubusercontent.com/16152743/53399538-2faa6400-397a-11e9-9498-ec86857a2a35.png)

Could you please tell me what am I missing, thanks!

**Comment by mbufi** [comment]
I am having the same issue! Have you resolved this?

**Comment by Kelvinson** [comment]
nope, hope someone can patch it to be compatible with the latest version of Pytorch.

**Comment by mbufi** [comment]
People who have had the same issues with CUDA out of memory report it has to do with batch size. I will have to investigate more with regards to this.

**Comment by mbufi** [comment]
Seems like when I run it I fail at the following line: 
`        # Pass input data through model
        output_prob, state_feat = self.model.forward(input_color_data, input_depth_data, is_volatile, specific_rotation)`

It will call this function and fail. Not sure how I do not have enough memory for this? 

`def forward(self, input_color_data, input_depth_data, is_volatile=False, specific_rotation=-1):`

**Comment by md3011** [comment]
I am facing the same issue. Were you able to resolve this?

**Comment by mbufi** [comment]
No I was not able to.

**Comment by st2yang** [comment]
Can you try to change torch.no_grad() to with torch.no_grad(): and put the following contents in its block.
https://github.com/andyzeng/visual-pushing-grasping/blob/support-pytorch-v0.4/models.py#L218

**Comment by st2yang** [comment]
Changing torch.no_grad() to with torch.no_grad(): and putting all the following contents in its block might fix the issue. (program can run but not fully tested)

https://github.com/andyzeng/visual-pushing-grasping/blob/support-pytorch-v0.4/models.py#L218

**Comment by mbufi** [comment]
@st2yang thanks for replying! Sorry but I do not understand the following " Changing torch.no_grad() to with torch.no_grad(): " 

I do not understand when you mean putting it all in a block. Do you mind elaborating more?
Thank you :smile:

**Comment by st2yang** [comment]
In PyTorch 0.4.0 and so on, volatile flag is deprecated and no_grad() is used to disable the grad propagation. But it might need to be like this 

`import torch

x = torch.zeros(1, requires_grad=True)
with torch.no_grad():
    y = x * 2
print(y.requires_grad)`

If you run other way

`import torch

x = torch.zeros(1, requires_grad=True)
torch.no_grad()
y = x * 2
print(y.requires_grad)`

You can still find y.requires_grad True.

The reason of this issue in Andy's code is that it didn't disable the grad computation in "inference" mode (when is_volatile=True), and there're 16 rotations in "inference" so the grad computation goes crazy. This is how I thought.

**Comment by Kelvinson** [comment]
@st2yang thanks for the pointer, I guess that's probably the reason. I can do a thorough migration to the  latest version and send a PR. BTW, do you think changing that will require a total retraining the model since it might change the computation underlying graph.

**Comment by st2yang** [comment]
That would be great if you are willing to migrate the project. I would recommend you to try to migrate to PyTorch 0.4.1 first and fully test it. Migrating to 0.4.1 should be much simpler and there is a pretty detailed official guide. And 0.4.1 is still widely used.

I think the provided weight file can still be used, at least for 0.4.1. The computation graph wouldn't change, and the weight file is saved in cpu mode and probably wouldn't cause dependency library version conflict issue.

**Comment by Kelvinson** [comment]
I did a not-thorough fix as @st2yang  pointed out and send a PR [here](https://github.com/andyzeng/visual-pushing-grasping/pull/25) 

A more thorough migration is on my [branch](https://github.com/Kelvinson/visual-pushing-grasping/tree/dong-patch-1.1), but it needs training from scratch and there is nan error during training.

Note the both of two branches **only work for V-REP 3.5**. A hack around to adapt V3.6 is welcome.  Let me know if you  have any problems.

**Comment by gsbandy24** [comment]
Does this occur for you when you attempt to train the VPG policy or the reactive method?

I don't have this error when trainining VPG, but when i try to train the baseline "reactive" methods, i have this cuda memory error. Just want to see if my issue is the same as yours or a tad different.
