### ISSUE TITLE
out of range

### ISSUE THREAD

**Issue by WwYyFan** [andyzeng/visual-pushing-grasping#15]
```
Connected to simulation.
Traceback (most recent call last):
  File "main.py", line 449, in <module>
    main(args)
  File "main.py", line 69, in main
    is_testing, test_preset_cases, test_preset_file)
  File "/home/user/model/visual-pushing-grasping/robot.py", line 70, in __init__
    self.setup_sim_camera()
  File "/home/user/model/visual-pushing-grasping/robot.py", line 155, in setup_sim_camera
    self.bg_color_img, self.bg_depth_img = self.get_camera_data()
  File "/home/user/model/visual-pushing-grasping/robot.py", line 309, in get_camera_data
    color_img.shape = (resolution[1], resolution[0], 3)
IndexError: list index out of range

```

**Comment by TONG369** [comment]
you may get a popup window titled "Dynamics content" in your V-REP window. Select the checkbox and press OK.

**Comment by TONG369** [comment]
Hello,
 Recently I am also using this code to do robot pushing and grasping, is it convenient to leave a contact? Let us communicate and learn together. Thank you, are you Chinese? I am, my mailbox is 1563845456@qq.com, I am looking forward to your reply.
 Thanks,

**Comment by GoogleMike** [comment]
> ```
> Connected to simulation.
> Traceback (most recent call last):
>   File "main.py", line 449, in <module>
>     main(args)
>   File "main.py", line 69, in main
>     is_testing, test_preset_cases, test_preset_file)
>   File "/home/user/model/visual-pushing-grasping/robot.py", line 70, in __init__
>     self.setup_sim_camera()
>   File "/home/user/model/visual-pushing-grasping/robot.py", line 155, in setup_sim_camera
>     self.bg_color_img, self.bg_depth_img = self.get_camera_data()
>   File "/home/user/model/visual-pushing-grasping/robot.py", line 309, in get_camera_data
>     color_img.shape = (resolution[1], resolution[0], 3)
> IndexError: list index out of range
> ```

Hi, I meet the same question as yours.
Could you please help me？
The V-REP I'm using is 3.6.0, and torch is 0.3.1, which is the same as guide.
Is the version inappropriate?
