### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by me2george** [andyzeng/visual-pushing-grasping#2]
while running main.py, I got some error described in title.  Any solutions or suggestions for this issue?
My enviroment: windows10 with Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz   16GB RAM  cuda9.0 installed(with cudnn) with NVIDIA GTX 750TI.  And I use the code for pytorch 0.4.

Many thanks in advance.

![image](https://user-images.githubusercontent.com/31275128/40541323-e10ee0d8-604d-11e8-86e8-d3c0d3facfd5.png)

**Comment by cjbarb7** [comment]
From the Readme file:
"Running out-of-the-box with our pre-trained models using GPU acceleration requires 8GB of GPU memory"

Your 750 Ti doesnt have enough memory.
