### ISSUE TITLE
KeyError: 'unexpected key "push_color_trunk.features.denseblock1.denselayer1.norm.1.weight" in state_dict'

### ISSUE THREAD

**Issue by OMGdxy** [andyzeng/visual-pushing-grasping#3]
hello,when I run main.py, I got the error . Any solutions or suggestions for this issue?
My enviroment: ubuntu16.04 + python2.7+pytorch 0.3+V-rep3.5 ,running with only CPU.
thank you for your answer

**Comment by andyzeng** [comment]
Interesting. This error looks a bit like what you would get if you tried loading our pre-trained weights with pytorch 0.4. Just to confirm, could you run in your command line:
```shell
echo -e "import torch\nimport torchvision\nprint(torch.__version__)\nprint(torchvision.__version__)" | python2.7
```
and let me know what it prints out?

**Comment by OMGdxy** [comment]
Thanks for your reply.
 My torch is 0.3.1 version and torchvision is 0.2.1.
I did not run the demo, but I can train the VPG policy from scratch.

**Comment by andyzeng** [comment]
I see. The problem is that torchvision is 0.2.1 (recent update to support pytorch 0.4). Installing torchvision 0.2.0 should fix the mismatch:
```shell
pip uninstall torchvision
pip install torchvision==0.2.0
```

**Comment by OMGdxy** [comment]
Thanks for your guidance.
Now I can run the demo with pre-trained weights.
I'm a beginner in robot and AI. Your code is very helpful for my study.
Thank you very much.
