### ISSUE TITLE
The realsense.cpp doesn't work

### ISSUE THREAD

**Issue by Lightwingy** [andyzeng/visual-pushing-grasping#39]
I have a SR300 camera. When I installed the realsense SDK 2.0, I tried to run the realsense.cpp. However, it still have a problem.The problem is RealSense error calling rs2_pipeline_start_with_config. Should I change my camera to D415? Is there any error in realsense.cpp?
![2019-09-06 12-08-33屏幕截图](https://user-images.githubusercontent.com/37580133/64400525-350e0700-d09f-11e9-95ea-99c2b3912ad6.png)

**Comment by CzJaewan** [comment]
@Lightwingy Hi! How to solve it?

I got it about realsense problem like following:

 `catkin_ws/src/visual-pushing-grasping/realsense/realsense.cpp:208:61: error: no match for call to ‘(rs2::colorizer) (rs2::depth_frame&)’
         rs2::frame depth_colorized = color_map(aligned_depth); 

                                                   ^
CMakeFiles/realsense.dir/build.make:62: recipe for target 'CMakeFiles/realsense.dir/realsense.cpp.o' failed
make[2]: *** [CMakeFiles/realsense.dir/realsense.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/realsense.dir/all' failed
make[1]: *** [CMakeFiles/realsense.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Lightwingy** [comment]
Please  refer to the issue #19.
