### ISSUE TITLE
`Dynamics content` warning when simulating

### ISSUE THREAD

**Issue by ElectronicElephant** [andyzeng/visual-pushing-grasping#61]
Hi all, 

I followed the official `README` and got this warning when simulating.

![image](https://user-images.githubusercontent.com/20351686/88305551-39392680-cd3c-11ea-9bd2-808fdba18751.png)

I'm new to this area so I'm wondering if I can ignore it.

I have tried version 4.0, 3.6.0, and 3.5, but no luck.

Thanks.

**Comment by kroglice** [comment]
That's normal just place the check and press ok like 10 times and after that, it will never appear.

**Comment by ElectronicElephant** [comment]
> 
> 
> That's normal just place the check and press ok like 10 times and after that, it will never appear.

Hi @kroglice , 

Get it. Thanks a lot!
