### ISSUE TITLE
Changes needed to use UR3 instead of UR5?

### ISSUE THREAD

**Issue by gab-es21** [andyzeng/visual-pushing-grasping#63]
I'm making a work at university, and I need to use UR3 instead of UR5 to a pick-and-place task, and I've changed the robot in simulation, but when I change the joints mode to Inverse Kinematic mode the robot breaks. What can I do to UR3 can work?
There are  any other modifications needed in the simulation or in the code beside changing UR5 to UR3 in robot.py ?
Thanks in advance.

**Comment by MengsiCode** [comment]
Just load the model, UR3.ttm, and in the robot.py, change the name of the handles (for example, UR5_target would be UR3_target). Since you say your robot breaks, check your joints, make sure they are in torque/force mode. If they are in kinematic mode, make sure hybrid is selected.
