### ISSUE TITLE
The camera D415 failed to produce the relevant scene image 

### ISSUE THREAD

**Issue by Bensonwyz** [andyzeng/visual-pushing-grasping#69]
When I reproduced Andy Zeng's visual-pushing-grasping on a real robot, I could not get out of this while loop. And the camera D415 failed to produce the relevant scene image. I don't know what the problem is. I would be very grateful if I can get some guidance and suggestions.

code in camera.py：
`
41        while len(data) < (10*4 + self.im_height*self.im_width*5):
42            data += self.tcp_socket.recv(self.buffer_size)
`

![1](https://user-images.githubusercontent.com/45646210/101302868-b1316480-3877-11eb-940a-d7b46b8cc9ec.png)

**Comment by Bensonwyz** [comment]
![2](https://user-images.githubusercontent.com/45646210/101317426-76402880-3899-11eb-96de-c6183089ab87.png)
I can see the scene information in the camera, but the camera does not return information, so I guess the camera didn't get the image, which led to an infinite loop. But I see that the information written in the code does not seem to be an image but an array of floats. I really don’t know how to proceed, I hope I can get some guidance and inspiration.

# Fetch TCP data:
        #     color camera intrinsics, 9 floats, number of bytes: 9 x 4
        #     depth scale for converting depth from uint16 to float, 1 float, number of bytes: 4
        #     depth image, self.im_width x self.im_height uint16, number of bytes: self.im_width x self.im_height x 2
        #     color image, self.im_width x self.im_height x 3 uint8, number of bytes: self.im_width x self.im_height x 3

**Comment by Bensonwyz** [comment]
I  found that np.fromstring() is used to parse images after checked the code below the while loop, but I don't know whether the program should generate an image first, or generate a string to return. What should I do to get such information?

        # Reorganize TCP data into color and depth frame
        self.intrinsics = np.fromstring(data[0:(9*4)], np.float32).reshape(3, 3)
        depth_scale = np.fromstring(data[(9*4):(10*4)], np.float32)[0]
        depth_img = np.fromstring(data[(10*4):((10*4)+self.im_width*self.im_height*2)], np.uint16).reshape(self.im_height, self.im_width)
        color_img = np.fromstring(data[((10*4)+self.im_width*self.im_height*2):], np.uint8).reshape(self.im_height, self.im_width, 3)
        depth_img = depth_img.astype(float) * depth_scale
        return color_img, depth_img

**Comment by jokerlu123** [comment]
Hello, friend,have you solved your problem? l used ur5e and d435i, and the same problem occurred. lf you solve it, could you tell me about the code modification part,thank you very much!

**Comment by Muyuoop** [comment]
> Hello, friend,have you solved your problem? l used ur5e and d435i, and the same problem occurred. lf you solve it, could you tell me about the code modification part,thank you very much!

Hello, I also use ur5e and d435i. Can you communicate with me? I have now resolved this issue. My email: hoiop8237@gmail.com
