### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by vRicardo98** [andyzeng/visual-pushing-grasping#70]
Hello Andy,
I am facing the cuda out of memory error when trying to train the model from scratch.
If you could help me, is there a way to reduce the batch size of training, or the resolution of the images given to the network for training, or even another possibility to overcome this error?

I am trying to run it on a 1050Ti, i7 7700hq and 32GB ram.

Regards,
Ricardo.

**Comment by elevenjiang1** [comment]
I work on it,but of course need to remove the backpropagate,just run the network forward.Need 2GB memory,tested on GTX1060
Use torch==0.3.1
1.main.py
main.py->line301
#trainer.backprop(prev_color_heightmap, prev_valid_depth_heightmap, prev_primitive_action, prev_best_pix_ind, label_value)
main.py->line 347
#with torch.no_grad():

add below main.py->406
         print('Time elapsed: %f' % (iteration_time_1-iteration_time_0)) #already exist
        torch.cuda.empty_cache()#new added


2:models.py:
models.py->line 216
#with torch.no_grad():

**Comment by vRicardo98** [comment]
Thanks @elevenjiang1! Your comment help me test training in my GPU.
Do you think that a lower version of torch, like the one you said and not commenting the backpropagation, could also work? Or torch doesn't have anything to do it and it is just that backpropagation consumes a lot of resources?

Thanks again!
Regards.

**Comment by elevenjiang1** [comment]
Sorry for that I can not understand what you say all.
commenting the backpropagation can help you run the network forward .However ,if you want to run backward ,it may need 12GB(mentioned by the author ).Your 1050Ti can not work .

Torch version is import .I can run on 0.3.0 and 1.2.0 (0.4.0can not run ).the error is somthing about '.' this maybe tochvision have conflict .the detail reason i also want to kown!

**Comment by luliangliangbeifeng** [comment]
I have the same problem that the terminal show that CUDA out of menmory when I run "python main.py --is_sim --method 'reactive' --experience_replay --save_visualizations". However everything is ok when I run "python main.py --is_sim --push_rewards --experience_replay --explore_rate_decay --save_visualizations". Do you know this is why?
Thank you!

**Comment by lgzid** [comment]
I have also encountered the same problem. Where can I reduce the batch size of training
