### ISSUE TITLE
How to know object sizes in simulation?

### ISSUE THREAD

**Issue by vRicardo98** [andyzeng/visual-pushing-grasping#72]
Hi! Sorry to bother you...

I am currently attempting to use VPG with a UR3 robot in simulation with CoppeliaSim.
Is it possible to obtain an object's bounding box size, assuming that I do not know the sizes of the objects in simulation, so I can possibly make some changes for a work I am studying?

Anxiously waiting for a reply,
Thanks.

**Comment by gsbandy24** [comment]
Hi, were you able to figure out this issue? Curious if it is solveable
